### ISSUE TITLE
Minimal KSnack position

### ISSUE THREAD

**Issue by niraj-prajapati** [onurkagan/KSnack#13]
How can i set minimal snack to bottom of screen?

**Comment by onurkagan** [comment]
you can not. if you want this feature, I can write today.

**Comment by niraj-prajapati** [comment]
actually i need to show it in bottom like connectivity status in youtube.
can you please add this feature? or please guide me how can i do that?

**Comment by onurkagan** [comment]
i will add this feature in 24 hours.

**Comment by niraj-prajapati** [comment]
> i will add this feature in 24 hours.

thanks

**Comment by onurkagan** [comment]
You can use `.alignBottom()` function on new version.

**Step 1 :** Use 1.1.2.
```
implementation 'com.github.onurkagan:KSnack:1.1.2'
```

**Step 2 :** Add `.alignBottom()` function. 
```
minimalKSnack
    .setTitle("bla bla")
    ....
    .alignBottom()
    .show()
```

**Comment by onurkagan** [comment]
If you need; you can use with fragment. This constructor is deprecated. Because does not work correctly when fragment root view is LinearLayout. You should use other layouts. Otherwise, the position of MinimalKSnack on the screen will be incorrect.

```
MinimalKSnack minimalKSnack   = new MinimalKSnack(BlankFragment.this);
```

**Comment by niraj-prajapati** [comment]
thanks, closing the issue.
