### ISSUE TITLE
**REQUEST**

### ISSUE THREAD

**Issue by Anis-Vikernes** [onurkagan/KSnack#7]
### **_Minimal KSnack:_**

- Add setPosition: _TOP || BOTTOM_

- Add isDismissable: _TRUE || FALSE_ 

> (if the user wants it to stay there and it doesn't get dismissed) 

- Add Slide down and Slide up animations

_Thank you for the the good effort you put on there! one of the best SnackBars libs out there!_

**Comment by onurkagan** [comment]
Hello. 
- You can use slide animation on version v1.1.0.
- You can make dissmisable with action button.
- Position has not been supported for snackview on material design.

### Animations

  #### 1. Fade
  ```java
 kSnack.setAnimation(Fade.In.getAnimation(), Fade.Out.getAnimation()) // show and hide animations
  ```
  
  #### 2. Slide
  ```java
 minimalKSnack.setAnimation(Slide.Up.getAnimation(minimalKSnack.getSnackView()), Slide.Down.getAnimation(minimalKSnack.getSnackView()))   
  ```
  Slide animations need KSnack or MinimalKSnack view. You should use ```getSnackView()``` or ```getMinimalSnackView()``` functions for correct view object.
